---
name: Math-SymbolicX-Calculator-Interface-Shell
version: 0.01
author:
  - 'Steffen Mueller <smueller@cpan.org>'
abstract: A Calculator Shell
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Math::Symbolic: 0.501
  Math::SymbolicX::Calculator::Interface: 0.01
  Params::Util: 0
  Parse::RecDescent: 0
  Term::ReadLine: 1.02
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
provides:
  Math::SymbolicX::Calculator::Interface::Shell:
    file: lib/Math/SymbolicX/Calculator/Interface/Shell.pm
    version: 0.01
generated_by: Module::Build version 0.280501
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
